### ISSUE TITLE
Azure Eventhubs Sink - partition parameter

### ISSUE THREAD

**Issue by tplevko** [apache/camel-kamelets#1005]
The partition parameter in [Azure Eventhub Sink](https://camel.apache.org/camel-kamelets/0.8.x/azure-eventhubs-sink.html)  in the last version is specified as:

```The Kamelet checks for the `partition` / `ce-partition` header to determine how long an event remains in the Azure Storage queue. Use `PnDTnHnMn.nS.` format. For example, `PT20.345S` parses as 20.345 seconds and `P2D` parses as 2 days.```

This is IMHO counterintuitive, as the [partition_key](https://camel.apache.org/components/3.18.x/azure-eventhubs-component.html#_endpoint_header_CamelAzureEventHubsPartitionKey) and [partition_id](https://camel.apache.org/components/3.18.x/azure-eventhubs-component.html#_endpoint_header_CamelAzureEventHubsPartitionId) in the Azure Eventhub Camel component is used for different purpose.

Could the name of the parameter be improved to something more descriptive?
Also - could be used the partition parameter for specifying the partition to be used by the kamelet, as in the Azure Eventhub Camel component?

**Comment by oscerd** [comment]
For the first question yes, we can name the parameter in a different way. For having partitionId as parameter of Kamelet, I don't agree totally, it's something that makes much more sense to have as dynamic parameter than fixed.
