### ISSUE TITLE
chuck-norris-kamelet HTTP error code 500

### ISSUE THREAD

**Issue by Croway** [apache/camel-kamelets#1042]
Hello,

http://icndb.com is offline, therefore the chuck-norris-kamelet cannot be used.

Some camel-quarkus and camel-spring-boot examples use that Kamelet.

**Comment by oscerd** [comment]
There is not so much we could do, except removing the Kamelet.

**Comment by davsclaus** [comment]
https://github.com/apache/camel-kamelets/pull/1043
