### ISSUE TITLE
Kamelet - Parameters that are enum based should have a way to define this in the spec

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-kamelets#1046]
For example the xj-action

the `direction` parameter
https://github.com/apache/camel-kamelets/blob/main/kamelets/xj-identity-action.kamelet.yaml#L38

Can only be `XML2JSON` or `JSON2XML` but this is only in the description. We should have a way like in regular Camel where we have `enum` that list the possible values.

**Comment by oscerd** [comment]
This should have been fixed through #1260
