### ISSUE TITLE
Kafka SSL SCRAM Login

### ISSUE THREAD

**Issue by rossdeane** [apache/camel-kamelets#1085]
Hi,
It doesn't seem to be possible to use a custom JAAS config with the Kafka-SSL Sink and Source. 
It should be possible to set `saslJaasConfig` in https://github.com/apache/camel-kamelets/blob/main/kamelets/kafka-ssl-source.kamelet.yaml

**Comment by oscerd** [comment]
We could add it, it will be in the 0.10.0 release, targeting Camel 3.19.0

**Comment by rossdeane** [comment]
Sure, I'll open a PR! Thanks

**Comment by oscerd** [comment]
Thanks for your time.

**Comment by MarcoMartins86** [comment]
I had this problem too, @rossdeane not sure if you were working on this, but I've opened a PR https://github.com/apache/camel-kamelets/pull/1093.
@oscerd Can you review it?

**Comment by rossdeane** [comment]
Hey sorry I didn't get around to submitting a PR, thanks for doing that @MarcoMartins86 :)
