### ISSUE TITLE
camel-kamelets-utils - Reduce dependencies in use

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-kamelets#1146]
The reuse of kamelets are more limited due to kamelets-utils are bringing in a number of depedencies that are for a specific Camel version.

We should try to reduce the number of dependencies if we can, and try to use only generic camel apis that does not change as much. This allows kamelets to be used across multiple Camel versions.

For example camel-kafka we only use some constant names for headers. Instead of we just use the String value instead and remove camel-kafka. 
https://github.com/apache/camel-kamelets/blob/main/library/camel-kamelets-utils/pom.xml

**Comment by davsclaus** [comment]
Some of the util code could maybe also be moved to camel core project / components

**Comment by oscerd** [comment]
There is this draft which is somewhat related https://github.com/apache/camel/pull/8694

**Comment by oscerd** [comment]
The utils have been moved to camel-kamelets component. So this is outdated now.
