### ISSUE TITLE
FTP / SFTP connectors missing setting for binary mode transfers

### ISSUE THREAD

**Issue by brokenjacobs** [apache/camel-kamelets#1156]
This setting used to be called `camel.sink.endpoint.binary` and for some reason defaults to ASCII. I'd argue the default is wrong for most use cases too but if you transfer any files using this setting it will most likely change the contents of the file. Not desired for binary data. 

As an aside, why weren't all the missing arguments mapped into the Kamelet. Most of these were there for a reason... The ftp connector in particular is missing a lot of settings.

**Comment by oscerd** [comment]
Because Kamelets are not designed to be a replacement of a camel kafka connector connector. We are not able to maintain both ckc and camel-kamelets at the same time, so we need to focus on something and re-use it as building block for camel-kafka-connector.

**Comment by oscerd** [comment]
This should be available with 3.18.3 and 3.19.0 of ckc.

**Comment by brokenjacobs** [comment]
> Because Kamelets are not designed to be a replacement of a camel kafka connector connector. We are not able to maintain both ckc and camel-kamelets at the same time, so we need to focus on something and re-use it as building block for camel-kafka-connector.

Is there blog post or issue somewhere that explains why this was done? Using camelets for ckc?

**Comment by valdar** [comment]
Hello @brokenjacobs you can find the dev mailing list thread where the topic was discussed here https://lists.apache.org/thread/x1n54vqpb96p6b7wcwo3q89lptdd5p7d

I can add some context and my view: the idea of camel kafka connectors is to provide something that is tailored to an used case and works with minimal configuration that can be used with as little knowledge of camel as possible (ideally 0). 

There is a thread off between simplicity and flexibility: providing all the components with all the options is very flexible but kind of fail to address the above idea.

We thought that kamelets were a reasonable balance between providing a "packaged solution" and been flexible to add as many kamelets are needed.

In the process of moving from a solution to another obviously there are gaps to cover and thing to improve like the ftp kamelet that surely need some attention and improvement. 

That said we :heart:  contributions!

**Comment by brokenjacobs** [comment]
Thanks for the link. As a user of the Kafka connectors who hasn’t checked in for a while, and not a general user of Apache Camel, it has been super confusing trying to figure out what is going on. The mailing list thread link is very helpful.
