### ISSUE TITLE
SFTP / SCP connectors missing authentication options to use a private key

### ISSUE THREAD

**Issue by brokenjacobs** [apache/camel-kamelets#1157]
These settings collectively are:

`camel.sink.endpoint.privateKey` | Set the private key as byte so that the SFTP endpoint can do private key verification. 
`camel.sink.endpoint.privateKeyFile` | Set the private key file so that the SFTP endpoint can do private key verification. 
`camel.sink.endpoint.privateKeyPassphrase` | Set the private key file passphrase so that the SFTP endpoint can do private key verification. |
`camel.sink.endpoint.privateKeyUri` | Set the private key file (loaded from classpath by default) so that the SFTP endpoint can do private key verification.

Settings are also missing for hostkey checking, and providing a known hosts entry for the remote for validation:
`camel.sink.endpoint.strictHostKeyChecking`
`camel.sink.endpoint.useUserKnownHostsFile`

Setting a private key and known hosts file is usually done for ssh applications and is not possible with the current Kamelet.

**Comment by oscerd** [comment]
for SFTP this is a duplicate of: https://github.com/apache/camel-kamelets/issues/778

**Comment by oscerd** [comment]
I would avoid the privateKey parameter and just use the privateKeyFile
