### ISSUE TITLE
Errors with log-sink and log-action Kamelet

### ISSUE THREAD

**Issue by christophd** [apache/camel-kamelets#1227]
I am seeing errors in YAKS tests while using log-action Kamelet:

```
ERROR [io.qua.run.Application] (main) Failed to start application (with profile prod): org.apache.camel.ResolveEndpointFailedException: Failed to resolve endpoint: log://log-action?level=INFO&logMask=false&multiline=false&showAllProperties=false&showBody=true&showBodyType=true&showCachedStreams=true&showExchangePattern=true&showHeaders=false&showProperties=false&showStreams=false due to: There are 1 parameters that couldn't be set on the endpoint. Check the uri if the parameters are spelt correctly and that they are properties of the endpoint. Unknown parameters=[{showCachedStreams=true}]
```

Do we need to remove `showCachedStreams` property form the Kamelet?

**Comment by christophd** [comment]
same with log-sink Kamelet

**Comment by oscerd** [comment]
ShowCachedStreams is in 3.20.0-SNAPSHOT. it should be released soon. I think this is the problem. But need to double check

**Comment by tadayosi** [comment]
Yes, `showCachedStreams` is a new addition to 3.20.0 so it should be fixed once Camel is upgraded to 3.20.0.
https://camel.apache.org/components/next/log-component.html#_endpoint_options

**Comment by oscerd** [comment]
This is related to camel k runtime not aligned to 3.20.0, it should be something to report in camel k

**Comment by squakez** [comment]
I think we already fixed that, making `main` Camel K to depend on the latest Kamelets tag aligned with the expected Camel version.

**Comment by christophd** [comment]
@squakez I did rebase the PR on main branch but still the log-action Kamelet is not able to run properly with Camel K as shown in the tests https://github.com/apache/camel-kamelets/actions/runs/3872513218/jobs/6601438316#step:11:817

**Comment by squakez** [comment]
Camel K `main` is built against a stable relase of Kamelets `0.10.0`: https://github.com/apache/camel-k/blob/main/script/Makefile#L88 - this is because the latest version of Camel K still uses Camel 3.19. If you need a Camel K operator (and runtime) available for Camel 3.20, I guess you'll need to wait for the related update (which is mainly driven by Camel Quarkus).

**Comment by christophd** [comment]
Unfortunately this is not a good situation for the CI tests in this Kamelet catalog repository. They will keep failing until the Camel K runtime with Camel 3.20 is available.

I see an option to move from Camel K runtime to JBang in the tests in order to align with Camel 3.20. I really would like to keep Camel K runtime in Kamelets tests, too but waiting such a long time is not a good option IMO

**Comment by squakez** [comment]
Yes. As Kamelets are going to be completely decoupled from Camel K, it makes sense to use some other way of testing it against the latest Camel version.
