### ISSUE TITLE
Request for RabbitMQ Sink Kamelet

### ISSUE THREAD

**Issue by tbnguyen1407** [apache/camel-kamelets#1228]
Hello, we are using RabbitMQ Sink connector in v0.11.x of Camel Kafka Connector. This is no longer available in newer versions (v1.x and v3.x). Is there any plan to add support for this in near future? Thank you.

**Comment by tbnguyen1407** [comment]
Hello, please also include TLS configs for both source and sink (keystore, truststore related configs). Thannk you.

**Comment by oscerd** [comment]
If you are in a hurry you could also open a PR yourself. Rabbitmq has been deprecated and removed in camel 4. So we're going to use spring-rabbitmq component in main.

**Comment by oscerd** [comment]
We are doing the new Sink Kamelet in #1889
