### ISSUE TITLE
Add Salesforce sink kamelet

### ISSUE THREAD

**Issue by claudio4j** [apache/camel-kamelets#124]
I am working on it.

**Comment by claudio4j** [comment]
Not working in this at this moment.

**Comment by 2020testuser** [comment]
@claudio4j - Is there a link that provides Salesforce sink kamelet details?
Thanks!

**Comment by claudio4j** [comment]
There is this  https://gist.github.com/davsclaus/db545d550207364e30515c13649d9f5b

**Comment by 2020testuser** [comment]
@claudio4j - Could you please let me know how to use the above link? Would updating the yaml for salesforce credentials, would work? Any info. would really help me as new to this area. Thanks in advance!

**Comment by oscerd** [comment]
This should be done.
