### ISSUE TITLE
ElasicSearchSink-TrustCertificates

### ISSUE THREAD

**Issue by mthirion** [apache/camel-kamelets#1246]
When using the "elasticsearch-index-sink" kamelet wit SSL enabled, I receive : "PKIX path building failed: unable to find valid certification path to requested target".
Is there a way to add a truststore or to ignore hostname verification?

**Comment by oscerd** [comment]
You need to specify certificatePath

**Comment by oscerd** [comment]
If you are using the main branch, you should pass a certificate file like described here https://github.com/apache/camel-kamelets-examples/tree/main/jbang/timer-elasticsearch-index

**Comment by oscerd** [comment]
This will work with 3.21.0 release. With 3.20 you still have the old kamelet and with that there is no way to specify a trust store, unless you create your own kamelet

**Comment by mthirion** [comment]
Ah yeah, ok, that's my version indeed.  I'll get to the next one.

**Comment by oscerd** [comment]
This is mainly because the old version was based on the rest component, while the new one has been based on the java client 8.x..

**Comment by oscerd** [comment]
3.21.0 has been released
