### ISSUE TITLE
kamelets catalog 3.20.1 contains some SNAPSHOT dependencies

### ISSUE THREAD

**Issue by valdar** [apache/camel-kamelets#1252]
If you look at `aws-ddb-experimental-sink` kamelet in `org.apache.camel.kamelets:camel-kamelets-catalog:3.20.1` jar there is this dependency:
```yaml
dependencies:
  - github:apache.camel-kamelets:camel-kamelets-utils:3.20.1-SNAPSHOT
```
however release tag contains the correct one: https://github.com/apache/camel-kamelets/blob/v3.20.1/kamelets/aws-ddb-experimental-sink.kamelet.yaml#L112

**Comment by oscerd** [comment]
I think you are talking about camel-kamelets:3.20.1 and not about camel-kamelets-catalog:3.20.1

**Comment by oscerd** [comment]
Release 3.20.1.1 is on vote.
