### ISSUE TITLE
Add an annotations to Kamelets to define the level of complexity

### ISSUE THREAD

**Issue by oscerd** [apache/camel-kamelets#1267]
Currently we are providing just
`
camel.apache.org/kamelet.support.level
`
with Stable, Preview and Experimental values.

I think it would be valuable to add a different label explaining the level of the Kamelets, like "Advanced", "Ready for Prod" or "Development Only"

With this information we could be able to filter the Kamelets on camel-jbang but also on Kamel cli.

@davsclaus @lburgazzoli @squakez 

Ideas for the annotation name? And for possible values?

**Comment by oscerd** [comment]
pinging again @davsclaus @lburgazzoli @squakez

**Comment by davsclaus** [comment]
The 3 values today are also what other projects use such as Quarkus.
I would keep that as-is.

What we could do is to add a 2nd label/enum/note. Where a kamelet can be marked as "common", "advanced",  "development", ...

You can have a stable component but it can be advanced / special. 

I dont think we should label stuff as "ready for prod" that is end user that decide what to use. But for prod you would favour using "Stable" kamelets and maybe in some cases "Preview" for newly added kamelets.

**Comment by davsclaus** [comment]
PS its a bit ironic that a kamelet can become complex, they were intended as more simpler building blocks that regular Camel components.

**Comment by oscerd** [comment]
Well, the idea was to give some idea of what you're going to use. For example the event sourcing Kamelets, are a bit more complex then the plain ones, they are still building blocks, with some more complexity. So the idea was having something aside the support level based on components and add something related to Kamelets only.

**Comment by davsclaus** [comment]
okay maybe the kamelets should have a 1..N labels so you can mark them with "event sourcing", "messaging", "database", "cloud", eg like we do for components today.

like you can see with jbang

camel catalog component --filter=database

**Comment by davsclaus** [comment]
you can find a bit ala

camel catalog kamelet --filter=file

but it checks also the description which is free form text.

**Comment by oscerd** [comment]
Maybe adding a label for the Kamelet level is too much, we'll end to have too much information. Maybe categorizing could be better, we already have a group field, but it's related to a logic group. I'll see what we could do.

**Comment by davsclaus** [comment]
you could grab the category we have in components already (its called label)
https://github.com/apache/camel/blob/main/components/camel-aws/camel-aws2-s3/src/generated/resources/org/apache/camel/component/aws2/s3/aws2-s3.json#L9

**Comment by oscerd** [comment]
I added the namespace field, so we have some kind of differentiation
