### ISSUE TITLE
Is there any kind of SMT available in camel-kamelets

### ISSUE THREAD

**Issue by 5olitude** [apache/camel-kamelets#1309]
I am sending data from kafka in  the form of json to the sink datasource but it is not populated in the supposed database ,but array of data working fine [1,"Alice"] and its added to the rows .  I already saw an issue regarding this  in camel-kafka-connector  but the solution was to make a custom  smt  , Let me know whether there is a field available in yaml of kamelets to add custom smt .      
I want to add the data in the below format to the cassandra db                  

```
[{
    "id" : "1",
    "name" : "Alice",
} ]
```                                                                       

https://github.com/apache/camel-kafka-connector/issues/1487

**Comment by oscerd** [comment]
No, there is not. Since Kamelets are generic and not only for Kafka Connect framework, there is no point in having a field for SMTs in their YAML. You should create your own SMT.
