### ISSUE TITLE
 Bind variables cannot be used for table names 

### ISSUE THREAD

**Issue by 5olitude** [apache/camel-kamelets#1310]
how can  I bind kafka values as bind variables for sink connector

**Comment by oscerd** [comment]
Please explain a bit better what you're trying to do and maybe add some code and examples.

**Comment by 5olitude** [comment]
insert into table_name(id, name) values (?,?)    : This is my query but I need to replace the table name along with kafka returned value , suppose if my kafka values are like this [table_name,id,name] how can I assign the table_name to the above query?    Im using Cassandra sink connector

**Comment by oscerd** [comment]
This is not possible at this stage. The bind is just for values not for the table name. You could try to manipulate the table name through modifying the Kamelets and change the sink from to to toD, but it's conceptually wrong for Kamelets.

If you have multiple tables, you should have a kafka topic for each of them and consume with n kamelets one for each table. Kamelets are building blocks, not all the use cases could be covered.
