### ISSUE TITLE
Deprecating parameters

### ISSUE THREAD

**Issue by manstis** [apache/camel-kamelets#1330]
By way of a real example, let me explain the issue:

The Camel Slack Component has deprecated some [Query Parameters](https://camel.apache.org/components/3.20.x/slack-component.html#_path_parameters_1_parameters), namely `iconEmoji`, `iconUrl` and `username`.

Ideally the corresponding [Slack Sink Kamelet](https://camel.apache.org/camel-kamelets/3.20.x/slack-sink.html) needs the parameters to be marked as deprecated too so Users are aware that they may be removed in a future release.

However the underlying [`Kamelet.KameletSpec.JSONSCHEMAPROPS.JSONSCHEMAPROP`](https://camel.apache.org/camel-k/1.12.x/apis/kamelets.html#_camel_apache_org_v1alpha1_JSONSchemaProp) does not support indicating that a parameter is deprecated.

What can we do?

Add a property to https://camel.apache.org/camel-k/1.12.x/apis/kamelets.html#_camel_apache_org_v1alpha1_JSONSchemaProp

Propose use of an `x-descriptor` to indicate the parameter is deprecated? What would it be? 

Where would we also need to presumably change Kamelet documentation generation to use the new property or x-descriptor?

**Comment by oscerd** [comment]
As of today there is no concept of deprecation in Kamelets parameters nor on Kamelets in general. So this would be something completely new.

**Comment by manstis** [comment]
Hi @oscerd I realise it's new.

I'm happy to collaborate as best I can; but am likely to need a little direction.

You may have guessed I'm new to Kamelets (and Camel as a whole too) but am eager to be useful.

I assume there's a process and this issue is likely to need discussion and a solution agreed.

If you're happy guiding, I'm happy helping.

**Comment by oscerd** [comment]
I'll gather some idea like where to change the documentation generation and the schema. Thanks for helping.

**Comment by oscerd** [comment]
This is where the documentation is generated for each Kamelet

https://github.com/apache/camel-kamelets/blob/main/docs/modules/ROOT/examples/js/kamelets.js

**Comment by manstis** [comment]
See https://github.com/apache/camel-k/pull/4097

I couldn't get the validation to use a local version of `camel/v1alpha1/Kamelet` for love nor money.

I'll keep trying (I'm learning Go too).
