### ISSUE TITLE
CouchBase source kamelet

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-kamelets#1331]
We have a sink. It would be good to have a source also
https://camel.apache.org/camel-kamelets/3.20.x/couchbase-sink.html

**Comment by oscerd** [comment]
https://github.com/apache/camel-kamelets/issues/542

**Comment by oscerd** [comment]
There are troubles because they are shading jackson-databind.

**Comment by oscerd** [comment]
Duplicate

**Comment by oscerd** [comment]
Duplicated see #542
