### ISSUE TITLE
SFTP source - it creates a new folder (if doesn't exist) instead of throwing an exception

### ISSUE THREAD

**Issue by mkralik3** [apache/camel-kamelets#1345]
According to the description[1] 
```
Whether to ignore when (trying to list files in directories or when downloading a file), which does not exist or due to permission error. By default when a directory or file does not exists or insufficient permission, then an exception is thrown. Setting this option to true allows to ignore that instead.
```
when the `ignoreFileNotFoundOrPermissionError` option is set to `false` (by default) and the folder (set in `directoryName`) doesn't exist, the connector should throw an exception. 
However, if the folder doesn't exist, the connector creates it instead.

[1] - https://github.com/apache/camel-kamelets/blob/main/kamelets/sftp-source.kamelet.yaml#L89 / https://camel.apache.org/components/3.20.x/sftp-component.html#_endpoint_query_option_ignoreFileNotFoundOrPermissionError

**Comment by oscerd** [comment]
This is related to: https://camel.apache.org/components/3.20.x/sftp-component.html#_endpoint_query_option_autoCreate
since autocreate is always true, the starting directory will be created.
To fix this we need to expose the parameter and make it configurable.
