### ISSUE TITLE
Remove Solr Kamelets

### ISSUE THREAD

**Issue by oscerd** [apache/camel-kamelets#1456]
With CAMEL-19290 the component will be removed in 4.x

**Comment by Paul-Blanchaert** [comment]
@oscerd 
Now that we refactored camel-solr (https://issues.apache.org/jira/browse/CAMEL-21479) and re-instated camel-quarkus-solr (https://github.com/apache/camel-quarkus/issues/6806), would it be possible to revive the solr kamelets?
If so, how should we proceed?

**Comment by oscerd** [comment]
Sure thing. I can work on that. Let me open a new issue for this purpose and thank for reminding me.
