### ISSUE TITLE
CI enablement on PPC64le for Camel-kamelets

### ISSUE THREAD

**Issue by shreyakajbaje** [apache/camel-kamelets#1549]
Hi @oscerd we are willing to enable CI support for ppc64le(power) architecture. We have build camel-kamelets locally on power using the command ./mvnw -Dmaven.test.failure.ignore=true clean install. also is deploy target required. let us know further steps.

**Comment by oscerd** [comment]
We don't have access to power PC. There is a machine on Jenkins.

**Comment by shreyakajbaje** [comment]
thanks for the reply @oscerd. These power nodes are shared by ASF https://jenkins-ccos.apache.org/view/Shared%20-%20ppc64le%20nodes/ and we also don't have access to it. request you to check with ASF. Please let us know if anything further is required.

**Comment by oscerd** [comment]
We don't need to build on power PC. You can eventually reach out to ASF infra if you want to build on the node. It's not a priority and I don't really see why we should set up this.

You can have a look at the jenkinsfile on the camel repository and copy from there.

**Comment by oscerd** [comment]
We are open to contributions, but it's not a critical task

**Comment by shreyakajbaje** [comment]
Hi @oscerd we have ASF nodes that we can use to enable CI for camel-kamelets. Also could you please confirm ./mvnw -Dmaven.test.failure.ignore=true clean install command would work or deploy target is required

**Comment by oscerd** [comment]
Hello, all looks good and target is not needed. Cheers

**Comment by shreyakajbaje** [comment]
Thanks @oscerd #1581 looking forward to CI enablement

**Comment by oscerd** [comment]
https://ci-builds.apache.org/job/Camel/job/Camel%20Kamelets%20(ppc64le)/job/main/2/console

**Comment by oscerd** [comment]
Build is green.
