### ISSUE TITLE
Update apiVersion in kamelets to v1

### ISSUE THREAD

**Issue by claudio4j** [apache/camel-kamelets#1562]
- Change the KameletBinding to Pipe and the apiVersion to v1

**Comment by apupier** [comment]
I guess KameletsCatalog must be updated too https://github.com/apache/camel-kamelets/blob/2501406adba5b8751c4caa23793aa428ac1df451/library/camel-kamelets-catalog/src/main/java/org/apache/camel/kamelets/catalog/KameletsCatalog.java#L43-L45

**Comment by apupier** [comment]
Trying to gather what needs to be modified for the move from kameletBinding to Pipe:
- doc
- function name https://github.com/apache/camel-kamelets/blob/5c44e19587fd96c3736163d526c155af9218f39f/docs/modules/ROOT/examples/js/kamelets.js#L164
- folder name https://github.com/apache/camel-kamelets/tree/5c44e19587fd96c3736163d526c155af9218f39f/templates/bindings
- kind in binding files, fo rinstance https://github.com/apache/camel-kamelets/blob/5c44e19587fd96c3736163d526c155af9218f39f/templates/bindings/camel-k/ftp-sink-binding.yaml#L2 whcih will need to change the api version too I guess
- name of binding file, for instance https://github.com/apache/camel-kamelets/blob/5c44e19587fd96c3736163d526c155af9218f39f/templates/bindings/camel-k/ftp-sink-binding.yaml#L2
- Yaks test case https://github.com/apache/camel-kamelets/blob/5c44e19587fd96c3736163d526c155af9218f39f/test/data-type-action/data-type-action.feature#L16 (is Yaks already changed the name?)

**Comment by apupier** [comment]
Starting to work on this issue (I cannot assign it me)

**Comment by claudio4j** [comment]
Your proposal sounds good, I think everything is taken care of.
Thank you

**Comment by oscerd** [comment]
Not yet we need a release of 4.1.0 or 4.0.1 to complete this issue. There is a PR open waiting for the release. I think it is for yaks test
