### ISSUE TITLE
Yaks test job is reported in success despite test failure

### ISSUE THREAD

**Issue by apupier** [apache/camel-kamelets#1576]
for instance: https://github.com/apache/camel-kamelets/actions/runs/5852920053/job/15865959477#step:7:4546

```
Failed scenarios:
file:///home/runner/work/camel-kamelets/camel-kamelets/test/data-type-action/data-type-action.feature:10 # Create Kamelet binding

3 Scenarios (1 failed, 2 passed)
17 Steps (1 failed, 1 skipped, 15 passed)
```

**Comment by christophd** [comment]
thanks for reporting. I think this has already been fixed with 0.15.x

**Comment by apupier** [comment]
we should eb able to see it with https://github.com/apache/camel-kamelets/pull/1552 then

**Comment by apupier** [comment]
tested on a PR on my own repo so that a build is triggered and with 0.15.1, it is failing the job: https://github.com/apupier/camel-kamelets/actions/runs/5853652877/job/15868052153?pr=2
so now we have some tests to fix
