### ISSUE TITLE
Fix yaks test failing on main branch

### ISSUE THREAD

**Issue by apupier** [apache/camel-kamelets#1579]
Creating an epic to gather all failing tests and work to fix all of them:

 - [ ] [aws-ddb-sink-deleteItem.feature:45 # Verify AWS-DDB Kamelet sink binding](https://github.com/apache/camel-kamelets/actions/runs/5852920053/job/15865959477#step:7:559)
 - [ ] [aws-ddb-sink-updateItem.feature:47 # Verify AWS-DDB Kamelet sink binding](https://github.com/apache/camel-kamelets/actions/runs/5852920053/job/15865959477#step:7:2280)
 - [ ] [aws-s3-to-http.feature:22 # Verify AWS-S3 Kamelet to Http](https://github.com/apache/camel-kamelets/actions/runs/5852920053/job/15865959477#step:7:2956)
 - [ ] [avro-data-type.feature:3 # Create Kamelet bindings](https://github.com/apache/camel-kamelets/actions/runs/5852920053/job/15865959477#step:7:3377)
 - [ ] [avro-serdes-action.feature:3 # Create Kamelet bindings](https://github.com/apache/camel-kamelets/actions/runs/5852920053/job/15865959477#step:7:3714)
 - [ ] [data-type-action.feature:10 # Create Kamelet binding](https://github.com/apache/camel-kamelets/actions/runs/5852920053/job/15865959477#step:7:4449)

Note: they went unoticed failing because the job was reporting failure. it will be fixed with upgrade of yaks to 0.15.1 #1576

**Comment by christophd** [comment]
@apupier many thanks for getting this started

Let me know if I can help

**Comment by apupier** [comment]
I won't continue to investigate on this one. i do not even have a working Kubernetes/OpenShift platform locally (or with admin role) and not managed to have a Cucumber workspace correctly set neither in VS Code or Eclipse

**Comment by christophd** [comment]
Ok, thanks - I will have a look

**Comment by oscerd** [comment]
> Note: it started to fail with this build https://github.com/apache/camel-kamelets/actions/runs/5705996459/job/15461240012

It seems weird, it just regenerated the sbom, so it's something before

**Comment by apupier** [comment]
> > Note: it started to fail with this build https://github.com/apache/camel-kamelets/actions/runs/5705996459/job/15461240012
> 
> It seems weird, it just regenerated the sbom, so it's something before

agree it is weird.
The previous build is in success https://github.com/apache/camel-kamelets/actions/runs/5636526006/job/15268685724

Maybe linked to an external change?

**Comment by oscerd** [comment]
Morning, I would like to release camel-kamelets 4.0 soon, what's the status on this?

**Comment by christophd** [comment]
good morning. I will have a look today so I should be able to at least estimate the fixing by the end of the day

**Comment by christophd** [comment]
Fixed tests with #1586 using YAKS 0.15.1 and Camel 4.0.0

PR test run has been successful. Let's see how it behaves in the next days. Maybe some flaky test gets revealed and I will deal with it then
