### ISSUE TITLE
Warning during build due to peter-evans/create-pull-request@v3 using node12

### ISSUE THREAD

**Issue by apupier** [apache/camel-kamelets#1588]
```
The following actions uses node12 which is deprecated and will be forced to run on node16: peter-evans/create-pull-request@v3. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
```

v5 is available https://github.com/peter-evans/create-pull-request/releases/tag/v5

**Comment by oscerd** [comment]
Solved through https://github.com/apache/camel-kamelets/pull/1587

**Comment by apupier** [comment]
This is a different plug-in, the warnign is stil lhere this one: https://github.com/apache/camel-kamelets/actions/runs/5954056163
