### ISSUE TITLE
Can we remove the tectonic.ui crap

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-kamelets#1700]
The kamelets should be clean and neutral. 

All this kind of stuff should be removed.

        x-descriptors:
        - 'urn:alm:descriptor:com.tectonic.ui:checkbox'

**Comment by oscerd** [comment]
This was when Kamelets were associated only to camel k

**Comment by davsclaus** [comment]
Maybe we can do a grep from terminal and find out approx how many x-descriptors there are to understand how big a work this is

**Comment by davsclaus** [comment]
Some of them can be replaced with enum #1699

**Comment by lburgazzoli** [comment]
some of those descriptors are leveraged by tools to i.e. show the properties on different places/wizard/whatnot.

the tectonic ones are leveraged by openshift's dev console so we may need to deprecate them before removing them

**Comment by oscerd** [comment]
I think this affects also Karavan and Kaoto, because they are using Tekton.

**Comment by christophd** [comment]
@Delawen @igarashitm 👀

**Comment by igarashitm** [comment]
We don't have any special use for that in Kaoto ATM

**Comment by oscerd** [comment]
So it seems only the openshift dev console would be affected

**Comment by christophd** [comment]
@vikram-raj could you please have a look and see how this would impact the ODC UI? many thanks

**Comment by christophd** [comment]
maybe also @invincibleJai please have a look. thx!

**Comment by oscerd** [comment]
@vikram-raj @invincibleJai please give feedback. I'm going to remove tectonic metadata next week.

**Comment by oscerd** [comment]
Removed. If there is any needs, Kamelets could be enriched directly by project using them
