### ISSUE TITLE
Release Camel Kamelets 4.6.0

### ISSUE THREAD

**Issue by oscerd** [apache/camel-kamelets#2029]

**Comment by christophd** [comment]
I have a pending fix on the Ddb2JsonStructDataTypeTransformer data type that has fixed the aws-ddb-streams-kamelet (see #2008)

We need a Maven jandex on the camel-kamelets-utils library so the Quarkus runtime properly retrieves the data type when using the Kamelet.

It would be good to include this into the 4.6.0 release. I will open a new PR for this

**Comment by oscerd** [comment]
Sure, feel free to create an issue and add it to the milestone.

**Comment by christophd** [comment]
see #2032 and the PR #2033

**Comment by christophd** [comment]
@oscerd do I need to backport to some branch or did you cut the 4.6.0 release branch after the change made in #2033

**Comment by oscerd** [comment]
It's part of the 4.6.0 release and it's on vote

**Comment by oscerd** [comment]
https://github.com/apache/camel-kamelets/commit/c8fc4eea90a56c5ba8128b1363db323a9c8ceeb2

**Comment by christophd** [comment]
> It's part of the 4.6.0 release and it's on vote
Awesome many thanks!

**Comment by oscerd** [comment]
On vote.

**Comment by oscerd** [comment]
Released
