### ISSUE TITLE
KameletCatalog is empty with a bundled jar

### ISSUE THREAD

**Issue by apupier** [apache/camel-kamelets#209]
it is workign fine when the project is opened in an IDE but it is empty when the jar is bundled.

The line 

https://github.com/apache/camel-kamelets/blob/0cb57a6e39b725af335634f9b9777b2b519ae496/library/camel-kamelets-catalog/src/main/java/org/apache/camel/kamelets/catalog/KameletsCatalog.java#L56

is returning an empty list.

note related to it:
I think it will also require to use "/" separator instead of File.separator and to use the / at the beginning of the path for abundled jar.

**Comment by oscerd** [comment]
Feel free to fix this

**Comment by oscerd** [comment]
Otherwise I'll fix it during the week
