### ISSUE TITLE
Add parameter for vhost in RabbitMQ Spring Source/Sink

### ISSUE THREAD

**Issue by Evynglais** [apache/camel-kamelets#2114]
Support for virtual hosts was added to the RabbitMQ source in #1068, but this appears to have been lost when moving to the Spring RabbitMQ Source.

The Spring RabbitMQ connection factory accepts a `virtualHost` parameter, so this is as simple as configuring the parameter on the Kamelets for Source/Sink.

**Comment by oscerd** [comment]
This requires virtualHost in the component on Camel first. So you need to raise a JIRA issue on https://issues.apache.org/jira/browse/CAMEL

**Comment by oscerd** [comment]
Thanks for the PR!
