### ISSUE TITLE
Add parameter to configure maxMessagesPerPoll for in aws-sqs-source Kemelet

### ISSUE THREAD

**Issue by jakubmalek** [apache/camel-kamelets#2118]
The {{Sqs2Endpoint}} can be configured with `maxMessagesPerPoll` parameter, which is translated into the [maxNumberOfMessages](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/sqs/model/ReceiveMessageRequest.html#withMaxNumberOfMessages-java.lang.Integer-) parameter for the AWSA SQS client.
The ` aws-sqs-source` Kamelet should be extended to support configuration is this parameter.

It should also be possible to configure the [visibilityTimeout](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/sqs/model/ReceiveMessageRequest.html#setVisibilityTimeout-java.lang.Integer-) and [waitTimeSeconds](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/sqs/model/ReceiveMessageRequest.html#setWaitTimeSeconds-java.lang.Integer-) parameters.

**Comment by oscerd** [comment]
This will go in 4.8.0 and so it will be in the next CKC 4.8.0 LTS release.

**Comment by jakubmalek** [comment]
@oscerd  I've already opened a [PR](https://github.com/apache/camel-kamelets/pull/2119) to add those parameters :)

**Comment by oscerd** [comment]
Great!

**Comment by oscerd** [comment]
I'll review later
