### ISSUE TITLE
Publish snapshots on Apache snapshots repository of the kamelet catalog

### ISSUE THREAD

**Issue by apupier** [apache/camel-kamelets#213]
This would allow consumer as Camel language Server to integrate it.

cc @nicolaferraro

**Comment by oscerd** [comment]
We can add a job on ASF CI for this or a GH Action too. Let me have a look.

**Comment by oscerd** [comment]
If @nicolaferraro is not working on this already obviously

**Comment by oscerd** [comment]
https://repository.apache.org/content/repositories/snapshots/org/apache/camel/kamelets/

The GH Action seems to have troubles of configuration on this repo, so I've done a Jenkins pipeline here:

https://ci-builds.apache.org/job/Camel/job/Camel-Kamelets%20Daily%20JDK11/

This will run every day and it is already working running by hands:

https://repository.apache.org/content/repositories/snapshots/org/apache/camel/kamelets/
