### ISSUE TITLE
Declare implicit dependencies

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-kamelets#214]
When it is about dependencies, the documentation states:

```
The Kamelet MAY declare dependencies on Camel components using the syntax camel:<component-name> 
(e.g. camel:telegram). Some Camel dependencies are implicitly added by the runtime when a certain Camel 
URI is used (e.g. there's no need to declare explicit dependency on camel:timer if the flow section uses the
timer URI).
```

This works fine for camel-k but in order to leverage the kamelets capabilities across different runtimes, i.e. camel-quarkus and camel-kafka-connect, it would be better if all the dependencies were explicitly listed.

**Comment by nicolaferraro** [comment]
I think we can also use kamel (or kamel bits) to auto-detect / auto-enhance the catalog

**Comment by valdar** [comment]
@nicolaferraro I will look into that, my initial idea was to:
1) add that detection of the missing implicit dependencies to the `script/validator`
2) initially make it fail validation hinting which dependencies to add.
3) add the call to validator to the "local build" through `mvn clean install`
