### ISSUE TITLE
Http/https Sink Kamelet: Expose okStatusCodeRange

### ISSUE THREAD

**Issue by oscerd** [apache/camel-kamelets#2219]
https://github.com/apache/camel-kafka-connector/issues/1675

**Comment by davsclaus** [comment]
No we should not just expose any half advanced options one by one on kamelets. A kamelet is not intended to cover everyones need. Especially a seldom option like ok ranges.

**Comment by oscerd** [comment]
Then we should find another way for ckc, like adding kamelets there directly.

**Comment by davsclaus** [comment]
Yeah we may consider making camel-kamelet able to provide additional parameters in some special way. However that is not tooling friendly.
