### ISSUE TITLE
Add labels related to kamelets trust level

### ISSUE THREAD

**Issue by oscerd** [apache/camel-kamelets#222]
We need to add a label for this purpose.

I'd like to discuss about:
1. Label name (it should be in metadata)
2. Level names. For example: Basic, Medium, High

What do you think? This would be useful even from a catalog perspective.

cc @nicolaferraro @lburgazzoli @valdar

**Comment by valdar** [comment]
Would that be a sort of "maturity level indicator" of the kamelet?

**Comment by oscerd** [comment]
Yes, something like that.

**Comment by davsclaus** [comment]
What if we have like in the other camel projects

- firstVersion: 1.0, 1.1, 1.2 and so on
- supportLevel: Stable, Preview, Experimental

Then its the same for an kamelet as it would be for a component, extension, etc.
