### ISSUE TITLE
Camel Splunk Hec: Token is not part of the URI, it's an endpoint parameter

### ISSUE THREAD

**Issue by oscerd** [apache/camel-kamelets#2318]
https://github.com/apache/camel-kafka-connector/issues/1692

**Comment by mackaw** [comment]
Is there any working version ?

**Comment by oscerd** [comment]
If you run through camel-kafka-connector there's no working version unless you build everything from scratch. If you use the Kamelet as it is, you can try to run it through camel-jbang https://camel.apache.org/manual/camel-jbang.html
