### ISSUE TITLE
Invalid label values

### ISSUE THREAD

**Issue by astefanutti** [apache/camel-kamelets#238]
I'm seeing the following error in Camel K:

```
could not create or replace camel.apache.org/v1alpha1, Kind=Kamelet aws-ddb-streams-source: Kamelet.camel.apache.org \"aws-ddb-streams-source\" is invalid: metadata.labels: Invalid value: \"AWS DynamoDB Streams\": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
```

Labels cannot contain spaces, as specified in https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set.

Unless there is a strong need to query Kamelets by group, `camel.apache.org/kamelet.group: "AWS DynamoDB Streams"` may be declared as an annotation.

**Comment by oscerd** [comment]
I put them as label and not as annotations. My bad. Will fix later or tomorrow. Sorry.

**Comment by astefanutti** [comment]
No worries. Thanks @oscerd.
