### ISSUE TITLE
Expose user-relevant options in kafka sources/sinks

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-kamelets#247]
I'm thinking to:
- clientId
- autoOffsetReset

But there may be others.

We can use the new optional placeholder for the clientId.

**Comment by nicolaferraro** [comment]
> Also allowManualCommit and autoCommitEnable should be exposed in some way.

Yes, we should also provide a way to do manual commit in case (e.g. an action).

**Comment by squakez** [comment]
> > I think for the source side, it's important to specify the pollOnError option, to specify how to behave in case of fail while polling one message.
> 
> Is there some relation to error handler? cc: @squakez

The `errorHandler`, if configured by user, is taking over when an exception arise either in the `source` or the `sink`. If there is some error managment done by the `Kamelet`, then, the `errorHandler` should not be triggered. However it would be good to double check these kind of behaviors.

**Comment by oscerd** [comment]
So now we have:
- autoCommitEnable
- allowManualCommit
- autoOffsetReset
- pollOnError

For clientId as optional, we need Camel 3.10
