### ISSUE TITLE
Hoist field should work with primitive types

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-kamelets#262]
I imagine it would be used sometimes to create a structure from plain data, such as a string. So it should not require a JsonNode, but it should work as well with primitive data as well (strings, booleans, numbers, ...).

**Comment by oscerd** [comment]
If you pass any kind of data it will work even with primitive types. Because it won't unmarshall in case of non json payload

**Comment by nicolaferraro** [comment]
> won't

Right, I've seen you already fixed it in last commit.
