### ISSUE TITLE
Allow serialization/deserialization of key

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-kamelets#317]
For Kafka usage, we should change the json serialize/deserialize to allow doing that on the key rather than the body.

If it does not complicate the interface, we may allow doing that on generic headers as well.

Wdyt @oscerd ?

**Comment by oscerd** [comment]
Yes, we can do that. By transforming the header json and re-insert it as transformed header, I guess.

**Comment by oscerd** [comment]
Lets park this for a while.

**Comment by oscerd** [comment]
Outdated
