### ISSUE TITLE
Support GCP pub sub kamelet

### ISSUE THREAD

**Issue by qafro1** [apache/camel-kamelets#396]
Pub/Sub works as a messaging middleware for traditional service integration or a simple communication medium for modern microservices.
Please is there any development for creating a GCP pub-sub kamelet?

**Comment by oscerd** [comment]
There is work to do for materializing the service account file as part of the configuration. At the moment you need to use 1.5.0-SNAPSHOT of camel-k to try it.

**Comment by oscerd** [comment]
also this is blocked by https://github.com/apache/camel-quarkus/issues/2796

**Comment by oscerd** [comment]
so at the moment it's not usable at all.

**Comment by matthewhembree** [comment]
I'm curious if anyone is using the PubSub Kafka [connector](https://github.com/GoogleCloudPlatform/pubsub/tree/master/kafka-connector) to proxy things through to the Kafka source kamelet.

My org already uses Kafka Connect, so it might not be too much a of a stretch to do this in the interim.

**Comment by matthewhembree** [comment]
..or I guess we could just use it in knative, native kafka event source. 🤦  🤷

**Comment by oscerd** [comment]
It should work, we are providing also the camel-kafka-connector for this purpose https://camel.apache.org/camel-kafka-connector/latest/reference/index.html

**Comment by oscerd** [comment]
With Camel-K 1.6.0 the Kamelets works fine. I just need to set it up and open PR.
