### ISSUE TITLE
Provide dependency info in each kamelet's catalog page

### ISSUE THREAD

**Issue by tadayosi** [apache/camel-kamelets#412]
Kamelets are now open for usage in standalone, but when we try to use them in a standalone app without some automatic dependency resolver like camel-kamelet-main it's cumbersome to know which extra component dependencies we need to put in `pom.xml`.

I think it's useful to provide a section in each catalog page that tells which components the kamelet uses. Does it make sense?

If it makes sense I can work on it.

**Comment by nicolaferraro** [comment]
Sure, it makes sense. You can also think to add specific sections about using them in particular environments (jbang?).

**Comment by tadayosi** [comment]
I now noticed that it's fixed months ago. Thanks @oscerd !
