### ISSUE TITLE
Move kamelets from root folder into a sub folder

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-kamelets#448]
There are soo many kamelets now it would be good to move them into their own sub folder, as we also have code for other stuff like the catalog api, and whatnot.

That helps the structure a bit, and also to look at the project on github as the readme file is shown sooner, than having to scroll long way down.

**Comment by davsclaus** [comment]
Need to talk to @lburgazzoli if this wont affect camel-k, as then the github url for the kamelet file would be changed.
also camel-kamelet-main needs to be aware as it also downloads from the root via github urls

Just created a ticket to find a way to organize the yaml files in a better way

**Comment by oscerd** [comment]
I'm planning to start working on this. @lburgazzoli @nicolaferraro can you please show reference of kamelet.yaml files path in the camel-k codebase? So I'll do multiple PRs in one time. Thanks.

**Comment by oscerd** [comment]
@davsclaus Can you show reference in main Camel repo? Thanks.

**Comment by davsclaus** [comment]
You can find some of it via
```
git grep "github:apache:camel-kamelets"
```

**Comment by davsclaus** [comment]
We use the 
https://github.com/apache/camel/tree/main/components/camel-resourceresolver-github

to download the official kamelets when using camel-jbang / camel-kamelet-main. And I think its only a matter of configuring the url location, from the previous comment.

However if they are located in different sub folders, then we cannot know where to look.

**Comment by oscerd** [comment]
I think it would be enough to have just one subfolder with all the yamls

**Comment by oscerd** [comment]
No multiple subfolders for the moment
