### ISSUE TITLE
Salesforce yaml

### ISSUE THREAD

**Issue by 2020testuser** [apache/camel-kamelets#457]
Hi, 
Could anyone please help me? I'm new to Kamelet and looking for some guidance.
I want to use the salesforce as source and call a python program as Sink.
I see the below link.

https://github.com/apache/camel-kamelets/blob/main/salesforce-source.kamelet.yaml.

1. How can I use the above link?
2. Do I need to install anything before using the above link?
Thanks in advance

**Comment by oscerd** [comment]
For the Kamelets usage and what we are talking about, please have a look at https://camel.apache.org/camel-k/latest/kamelets/kamelets-user.html

**Comment by 2020testuser** [comment]
@oscerd - I started with the link. Thanks Much!
