### ISSUE TITLE
topicName param

### ISSUE THREAD

**Issue by 2020testuser** [apache/camel-kamelets#459]
Hi,
Could anyone please let me know why the 'topicName' is a required field in the below yaml?
https://github.com/apache/camel-kamelets/blob/main/salesforce-source.kamelet.yaml

Also, if 'topicName' is a required field, how and where would I create the topic?

Thanks in advance!

**Comment by oscerd** [comment]
I think it's a wrong copy paste

**Comment by 2020testuser** [comment]
@oscerd - If you check the below link, the 'topicName' is a required field. Does that mean to use Salesforce source, I need Kafka to be installed in my Kubernetes cluster? Since, 'topicName' is a required field in the kamelet.yaml, trying to understand...

https://github.com/apache/camel-kamelets/blob/main/salesforce-source.kamelet.yaml
Thanks in advance!

**Comment by oscerd** [comment]
It's just an error, you can remove it and use the modified file. The documentation is autogenerated from the yaml file

**Comment by 2020testuser** [comment]
Thanks Much! Will do that.
