### ISSUE TITLE
replace-field-action is not adding the renames field to enabled list by default

### ISSUE THREAD

**Issue by hguerrero** [apache/camel-kamelets#460]
When using the replace-field-action I would expect that the fields in the `renames` section will automatically be added to the `enabled`, and not need to add them manually.

**Comment by oscerd** [comment]
What we are doing is similar to Kafka smt. Don't expect the same behavior.

**Comment by oscerd** [comment]
This has been fixed with #697 because the disabled and enabled fields are now not mandatory.
