### ISSUE TITLE
camel-kOperator Install

### ISSUE THREAD

**Issue by 2020testuser** [apache/camel-kamelets#469]
Hi,
Can anyone help me out please?
I'm installing camel-k in Linux. I uninstalled the tar package and used the below command to install kamel.
However, I don't see camel-k-operator pod in the pods list in my current namespace where I installed camel-k?

Could anyone please let me know how I can install camel-k-operator in my Kubernetes cluster? 

Thanks in advance!

**Comment by 2020testuser** [comment]
Thanks! Am I missing any step? Could you please check my steps above and let me know if I'm missing anything? Is there a bug. I believe not as no one reported on the issue yet.

**Comment by oscerd** [comment]
https://camel.apache.org/camel-k/latest/installation/installation.html

Those are the list of installation guide we currently support.

**Comment by oscerd** [comment]
So at first I would try one of these platforms.

**Comment by 2020testuser** [comment]
If I'm correct, the list doesn't have Kubernetes. So, Kubernetes is not supported for camel-k and kamel?

**Comment by oscerd** [comment]
I do not know how are you running yoyr kubernetes. Camel-k is for kubernetes. My suggestion is trying it on one of the listed platform like for example minikube. We cannot know how you're running your kubernetes and where. I also encourage you to read a bit more the documentation

**Comment by oscerd** [comment]
Closing this, re-open in case of more questions.
