### ISSUE TITLE
Adding filter for exluding explicit content to chuck-norris-source

### ISSUE THREAD

**Issue by rhuss** [apache/camel-kamelets#511]
I love the chuck-norris-source, and would like to use them in demos, but a bit afraid of showing up a quote like in https://api.chucknorris.io/jokes/7xoo4cjutwu3sgmuelp2pw during a customer demo ;-P While not necessarily not funny, it might confuse the audience a bit.

Would it be possible to add a filter from a bad-word list to https://github.com/apache/camel-kamelets/blob/fb004b99f4a54305ea5ec55b52944f2a8512bd0e/chuck-norris-source.kamelet.yaml#L39-L42 and just retry if a word of the list is matched? My Camel foo is unfortunately not good enough to add the corresponding steps ...

**Comment by rhuss** [comment]
I just see, that there is a field "explicit" in the jokes, so maybe better filter on that (and possibly allow an option for the sink to also allow explicit jokes)

**Comment by rhuss** [comment]
```json
{ "type": "success", "value": { "id": 71, "joke": "....", "categories": ["explicit"] } }
```

**Comment by nicolaferraro** [comment]
Yeah, there's also a filter in the URL, like: http://api.icndb.com/jokes/random?limitTo=[,nerdy]

If you just change that in the kamelet definition of your demo you should filter out explicit stuff.

We may also add an option in the Kamelet to toggle them.

**Comment by rhuss** [comment]
It would be cool, to allow a 'safe' set by default and only enable explicit things if, well, explicitly requested :). 

Also, if you set a category you also filter out all quotes without a category (which most of them are)

**Comment by rhuss** [comment]
I think http://api.icndb.com/jokes/random?exclude=[explicit] is it ...
