### ISSUE TITLE
aws-ec2 kamelets proposed improvement

### ISSUE THREAD

**Issue by valdar** [apache/camel-kamelets#516]
Since `aws-ec2-sink.kamelet.yaml` support just one of the possible operations (i.e. createAndRunInstances, startInstances, stopInstances, terminateInstances, describeInstances, describeInstancesStatus, rebootInstances, monitorInstances, unmonitorInstances, createTags, deleteTags) we can create one kamelet for each of those, or just have 2 kamelets:

- `aws-ec2-source.kamelet.yaml`: having a structure like  ` from(timer) .... to(aws2-ec2)...to(kamelet:sink)` and supporting the following operations:
    - `describeInstances` 
    - `describeInstancesStatus`
- `aws-ec2-source.kamelet.yaml`: having a structure like `from(kamelet:source)...to(aws2-ec2)` and supporting the following operations:
    - `createAndRunInstances` 
    - `startInstances` 
    - `stopInstances` 
    - `terminateInstances` 
    - `rebootInstances` 
    - `monitorInstances` 
    - `unmonitorInstances` 
    - `createTags` 
    - `deleteTags`

mind that I have assumed from the operations name what they would do, so someone more familiar with AWS can make more sense of this.

**Comment by oscerd** [comment]
Will have a look

**Comment by oscerd** [comment]
It would too complex to have a single kamelet for source and sink, because we'll have to deal with different headers combination. It probably makes more sense to have one kamelet for operation.
