### ISSUE TITLE
Documentation: Add information in active branches, about what is the camel-k version using the catalog

### ISSUE THREAD

**Issue by oscerd** [apache/camel-kamelets#632]

**Comment by djencks** [comment]
Is this a sub-task of https://github.com/apache/camel-website/issues/701? I was planning on tackling that next.

**Comment by oscerd** [comment]
Yes, i forgot to link the website issue. Thanks for it. Feel free to assign to yourself :-)

**Comment by oscerd** [comment]
@djencks is this done?

**Comment by djencks** [comment]
This is not yet implemented.  I'll try for today or tomorrow.

**Comment by djencks** [comment]
I implemented this in some PRs mentioning the camel-website issue, preview should be at https://pr-747--camel.netlify.app shortly,  however I fear that it will be extremely hard to keep these back-references updated correctly since the information is from another project.

**Comment by djencks** [comment]
I think this is done with the aforementioned PRs.
