### ISSUE TITLE
Add a "namespace" label to help group kamelets

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-kamelets#640]
As today we have a `kamelet.group` label that is used to group related kamelets together:

    camel.apache.org/kamelet.group: "AWS Cloudwatch"

It would be nice to add an additional label to define a larger group of related kamelets, like  `kamelet.namespace`:

    camel.apache.org/kamelet.namespace: "aws"

**Comment by oscerd** [comment]
Makes sense

**Comment by lburgazzoli** [comment]
or maybe review how the group is used and i.e instead of `AWS Cloudwatch`, just use `AWS` ?

**Comment by oscerd** [comment]
Originally it was done in that way because if we had multiple kamelets for the same AWS service, they would have been filtered in the site view. But yeah, makes sense too

**Comment by lburgazzoli** [comment]
or maybe we can use a convention like kamelet.group is always like namespace [+ kind] so in the case of `AWS Cloudwatch`, 

namespace = AWS
kind = Cloudwatch

**Comment by oscerd** [comment]
I think it should work in this way, I'm not sure if the annotations are currently used in camel-k too, need to have a look.
