### ISSUE TITLE
Split Github Source Kamelet in multiple Kamelets

### ISSUE THREAD

**Issue by oscerd** [apache/camel-kamelets#648]
I think it makes sense to change the Github Source Kamelet, to have multiple Kamelets for different entities, like tag, pullRequest, pullRequestComment.

We'll have:
- Fine grained configuration for Github consumer
- Specific option, for example startingSha while consuming commit
- Better catalog and better listing in Karavan

What do you think @davsclaus @lburgazzoli @nicolaferraro

**Comment by lburgazzoli** [comment]
+1

**Comment by davsclaus** [comment]
+1
