### ISSUE TITLE
Steps in KameletBinding accept also non-action kamelets resources

### ISSUE THREAD

**Issue by lfabriko** [apache/camel-kamelets#741]
I observed I can use also non-action kamelets in KameletBinding:
- produces correct output: klb timer-source (source) - kafka-sink (step) - log-sink (sink)
- produces no output: klb timer-source (source) - kafka-source (step) - log-sink (sink)
- produces null Body: klb timer-source (source) - Channel (step) - log-sink (sink)

**Comment by oscerd** [comment]
timer-source without message creates an empty body. So the behavior is correct.
