### ISSUE TITLE
Support key authentication in sftp kamelet

### ISSUE THREAD

**Issue by valdar** [apache/camel-kamelets#778]
since camel-sftp component support it, might be useful to support it at kamelet level as well.

**Comment by thibthibus** [comment]
Hi @valdar 
Any news on this change ?
We cannot upgrade to the new release of the Kafka Connector relying on kamelet as this feature is not available...
Thanks
KR,
Thibaut

**Comment by oscerd** [comment]
We will try to have it in 0.10.0 release, which will be 3.19.0 release of camel-kafka-connector.

You're welcome to provide a PR if you have time.

**Comment by oscerd** [comment]
This should be done on #1157
