### ISSUE TITLE
Organizing kamelets in sub folders or something else when we get a lot of kamelets

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-kamelets#79]
Maybe in not so long time, we have soo many kamelets in the root folder, that its gets harder to get an overview.

I wonder if we should start think about organizing kamelets in sub folders. And what impact that this have on the tool that build the kamelet web page, and other tools that may install a kamelet directly from github

**Comment by djencks** [comment]
I see three aspects to this:
1. I at least don't know what external tools or projects access the kamelets and what they expect
2. Having the Kamelets in the root folder of the code is extremely confusing
3. There are now enough Kamelets that the list is hard to search intelligently, so some kind of internal organization would be helpful.

If there's some kind of "standard" that Kamelets should be in the root of a git repo, then I suggest that (1) and (2) can be solved by using 2 git branches: a code branch and a production branch.  The code branch would have all the code and the master (sorry, I don't know what else to call it.... primary? original?? to me those have less clear meaning) copy of the kamelet, presumably under library/camel-kamelets/src/main/resources/kamelets, and a publication process would copy them to the root of the production branch, which would have nothing else in it.

This would let us solve (3) with perhaps a directory structure in  the library source copy while preserving the flat structure apparently expected by existing tools.

**Comment by davsclaus** [comment]
Yeah lets close this for now
