### ISSUE TITLE
kinesis improvements

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-kamelets#796]
source:
- As today the kinesis-source kamelet takes the record that is produced by the component and serializes it as json but given that the real payload of the record can be of any type, it would be better if the data of the rerecord were set as the exchange message body (this may be also an option we set on the camel component)
- if the above will be implemented the content type of the kamelet should be application/octet-stream

sink:
- the content type of the kamelet should be application/octet-stream

**Comment by oscerd** [comment]
We could extrapolate the data from record.
