### ISSUE TITLE
google-bigquery-sink credential file didn't read from my local

### ISSUE THREAD

**Issue by habibtalib** [apache/camel-kamelets#959]
Hi, 

I tried to configure credentialsFileLocation based on my local path. however it can't find. 
I tried to figure out to mount volume from configmap to read key file from pod. But there is no document helps. 

`apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: google-bigquery-sink-binding
spec:
  source:
    ref:
      kind: KafkaTopic
      apiVersion: kafka.strimzi.io/v1beta1
      name: test
  template:
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: google-bigquery-sink
    properties:
      credentialsFileLocation: ./bigquery-key.json
      dataset: test
      projectId: blacksmith-develop
      table: test
  errorHandler:
      log:
        parameters:
          maximumRedeliveries: 3
          redeliveryDelay: 2000`

The error is : 

`java.io.FileNotFoundException: ./bigquery-key.json (No such file or directory)`

**Comment by oscerd** [comment]
I suppose you're running this in a container, did you mount the volume with the credentials file? Because it doesn't seems so.

**Comment by oscerd** [comment]
Please re-open in case you need more help.
