### ISSUE TITLE
telegram-sink chat-id property must be required and/or have a default?

### ISSUE THREAD

**Issue by valdar** [apache/camel-kamelets#981]
I think that the chat id property in telegram-sink kamelet should be required, or if left optional provided with a default? otherwise the resulting deployed kamelet dose not even start.

I personally think that a default value does not make much sense. I would vote for making it required.

**Comment by oscerd** [comment]
Please open a PR

**Comment by manstis** [comment]
See https://github.com/apache/camel-kamelets/pull/1305
